[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
ronin_nft_bridge = "ApfDneee1WoxEEDK2vTxgUeD7FNwmg1Xw6Hn7eBHMwcS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/lazyjon/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -b -p ./tsconfig.json -t 10000000 sdk/tests/**/*.test.ts"
