import './common/wire'
import './common/send'
import './common/oappGet'
import './common/debug1155'
import './common/list1155'
import './common/check1155'
import './common/seed1155'
import './solana/oappCreate'
import './solana/initConfig'
import './solana/retryPayload'
import './solana/debug'
import './solana/initOnftAdapter'
import './solana/sendOnft'
import './solana/quoteOnft'
import './solana/setPeer'
import './solana/initLibs'
import './solana/initOAppConfig'
import './solana/debugLibs'
// removed: initEscrow (replaced by register-and-lock)
import './solana/splSend'
// removed: mapLock (replaced by register-and-lock)
import './solana/registerAndLock'
import './solana/onftDiagnose'
// removed: initOnftId (covered by set-registry-entry / register-and-lock)
import './solana/initRegistry'
import './solana/setRegistryEntry'
import './solana/claim'
import './solana/fixStoreDiscriminator'
import './solana/checkStore'
import './solana/fundStore'
import './solana/initPending'
import './evm/watchOnft'
